### ISSUE TITLE
Update image naming scheme and document it

### ISSUE THREAD

**Issue by BenDew21** [JoanneLin168/marioML#11]
The current image naming scheme is messy and should be updated and documented, so that all future features which require the use of images are done consistently.

Suggestion is to create a new folder under images for each character (for example, Mario and Luigi)

**Comment by JoanneLin168** [comment]
I was thinking, perhaps instead of using mario1.png, luigi20.png and test_wario1.png (just a few examples), we probably could just use 0.png, 1.png etc right? Especially since in issue 13 you have made them into folders separating the characters, it seems like a much more logical naming system

**Comment by JoanneLin168** [comment]
I don't mind doing the documentation for this, what would you think would be a suitable name for the file?

**Comment by BenDew21** [comment]
I added in a reference to it in README.MD under PR #13, but if you really wanted to make it an external document, these design decisions would usually go in a document known as an SDD (software design description), so marioML SDD seems logical.

**Comment by JoanneLin168** [comment]
@BenDew21 I think having a separate file would be more useful as a README file is generally used to describe what the program is and what it does

**Comment by JoanneLin168** [comment]
It can also be used to describe branch naming conventions and variable/function naming conventions, but that can be a in a separate style of code document I suppose
